on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
name: tests
env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        go-version:
          # support the two most recent major go versions
          - 1.x
          - 1.18.x
        platform: [ubuntu-latest]
        include:
          # minimum go version that works. This is not necessarily supported in
          # any way, and will be bumped up without notice as needed.  But it at
          # least lets us know what go version should work.
          - go-version: 1.17
            platform: ubuntu-latest

          # only update test coverage stats with most recent go version on linux
          - go-version: 1.x
            platform: ubuntu-latest
            update-coverage: true
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y libwebp-dev

      - name: Run go test
        run: go test -v -race ./...

